### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by smokeytube** [portalthree/JustEnoughDungeons#3]
I am a new java programmer, I transferred from python. How do I compile this? I ran gradlew.bat but no jar files were made. There are also some unresolved imports, is there a package manager for java?

**Comment by RedsLovesGames** [comment]
its a minecraft session id stealer

**Comment by Rhyn0w0** [comment]
no

**Comment by IamMusavaRibica** [comment]
If you are new to java I recommend learning fundamentals first

**Comment by ProfKambing** [comment]
install java 1.8.0 and gradle

do gradlew setupdecompworkspace
and gradlew build
